In [14]:
def add(a,b):
  return a+b

In [15]:
x=10
y=20
res=add(x,y)
print(res)

30


In [24]:
def student(name,age=21):
 print("Name",name)
 print("Age",age)
student("Rahul")

Name Rahul
Age 21


In [25]:
def student(name,age):
 print("Name",name)
 print("Age",age)
student("Rahul",25)

Name Rahul
Age 25


In [27]:
def student(name,age):
 print("Name",name)
 print("Age",age)
student(age=25,name="Rahul")

Name Rahul
Age 25


(*args),(**kwargs)

In [40]:
def add(a,b):
 return a+b

In [41]:
print(add(10,20))

30


In [38]:
def add(*num):
  for i in num:
    print(i)
  return sum(num)

In [36]:
def add(*num):
  total=0
  for i in num:
    total+=i
  return total

In [37]:
print(add(10,20))
print(add(10,20,30,40,50))

30
150


In [42]:
def student(**details):
  print(details)
student(name="Rahul",age=20,city="Agra")

{'name': 'Rahul', 'age': 20, 'city': 'Agra'}


In [17]:
def welcome():
  print("Welcome to Python Lab")
welcome()

Welcome to Python Lab


**Reshaping Arrays**

In [43]:
import numpy as np
data=np.arange(1,13)
print("Original data shape",data.shape)
a=data.reshape(3,4)
print("3x4 \n",a)
b=data.reshape(4,3)
print("4x3 \n",b)
c=data.reshape(2,-1)
print("2xinfer \n",c)

Original data shape (12,)
3x4 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4x3 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2xinfer 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


flatten() and ravel()

In [44]:
data=np.array([[1,2,3],[4,5,6]])
print(data.ndim)
flat1=data.flatten()
print("flat1 shape",flat1.ndim)
flat2=data.ravel()
print("flat2 shape",flat2.ndim)

2
flat1 shape 1
flat2 shape 1


In [45]:
data=np.array([[[1,2,3],[4,5,6]]])
print(data.ndim)
flat1=data.flatten()
print("flat1 shape",flat1.ndim)
flat2=data.ravel()
print("flat2 shape",flat2.ndim)

3
flat1 shape 1
flat2 shape 1


np.concatenate()

np.vstack()

np.hstack()

In [48]:
a=np.array([1,2,3])
b=np.array([7,8,9])
print("concatenate:",np.concatenate((a,b)))
print("vstack",np.vstack((a,b)))
print("hstack:",np.hstack((a,b)))

concatenate: [1 2 3 7 8 9]
vstack [[1 2 3]
 [7 8 9]]
hstack: [1 2 3 7 8 9]


In [50]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print("concatenate:",np.concatenate((a,b)))
print("vstack",np.vstack((a,b)))
print("hstack:",np.hstack((a,b)))

concatenate: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vstack [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
hstack: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**Vectorization**

In [57]:
data=np.array([10,20,40,50])
res=[]
for x in data:
  res.append(x*2)
print(np.array(res))

[ 20  40  80 100]


In [58]:
vecc_data=data*2
print(vecc_data)

[ 20  40  80 100]


In [59]:
a=np.array([[1,2,3]])
b=np.array([[7,8,9]])
print(a+b)
print(a-b)
print(a*b)

[[ 8 10 12]]
[[-6 -6 -6]]
[[ 7 16 27]]


In [54]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]


In [53]:
marks=np.array([50,60,70,80,90])
print(f'Add5:{marks+5}')
print(f'Sub5:{marks-5}')
print(f'Mul5:{marks*5}')


Add5:[55 65 75 85 95]
Sub5:[45 55 65 75 85]
Mul5:[250 300 350 400 450]


In [55]:
marks=np.array([35,45,52,68,74,81,90])
passed=marks >=40
between= marks[(marks>=50) & (marks<=80)]
print(f'Mask for marks >=40:{passed}')
print(f'Passing marks:{marks[passed]}')
print(f'Marks between 50 and 80:{between}')

Mask for marks >=40:[False  True  True  True  True  True  True]
Passing marks:[45 52 68 74 81 90]
Marks between 50 and 80:[52 68 74]


In [47]:
def square(n):
  return n*n
print(square(5))

25


In [7]:
import numpy as np
n= int(input("How many numbers"))
num=[]
for i in range(n):
  x=int(input("Enter number"))
  num.append(x)
arr=np.array(num)
print("Type:",type(arr))
print("Numpy Array:", arr)
print("Array Shape:", arr.shape)
print("Array Size:",arr.ndim)
print("Array type:",arr.dtype)

How many numbers4
Enter number1
Enter number2
Enter number3
Enter number4
Type: <class 'numpy.ndarray'>
Numpy Array: [1 2 3 4]
Array Shape: (4,)
Array Size: 1
Array type: int64


In [21]:
def create_Array(n):
 num=[]
 for i in range(n):
  x=int(input("Enter number"))
  num.append(x)
 return np.array(num)
y=int(input("How many numbers"))
arr=create_Array(y)
print(arr)

How many numbers4
Enter number1
Enter number2
Enter number3
Enter number4
[1 2 3 4]


**Broadcasting**

In [60]:
arr=np.array([1,2,3])
res=arr+1
print(res)

[2 3 4]


In [61]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
print(a+b)

[[ 8 10 12]
 [11 13 15]]


In [62]:
a=np.array([12,24,35,45,60,72])
b=np.array(["Adult","Minor"])
res=np.where(a>18,b[0],b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


In [63]:
m=np.array([[1,2],[3,4]])
v=np.array([10,20])
res=v*m
print(res)

[[10 40]
 [30 80]]
