In [ ]:
num=int(input("Enter an integer"))
print(type(num))

Enter an integer5
<class 'int'>


In [ ]:
for i in range(1,11):
  print(f'{num}x{i}={num*i}')

5x1=5
5x2=10
5x3=15
5x4=20
5x5=25
5x6=30
5x7=35
5x8=40
5x9=45
5x10=50


In [ ]:
a = float(input("Enter first number"))
b = float(input("Enter second number"))
print(f'Addition:{a+b}')
print(f'substraction:{a-b}')
print(f'Multiplication:{a*b}')
print(f'Division:{a/b}')
print(f'Floor division:{a//b}')
print(f'Remainder:{a%b}')
print(f'Exponent:{a**b}')

Enter first number4.5
Enter second number3
Addition:7.5
substraction:1.5
Multiplication:13.5
Division:1.5
Floor division:1.0
Remainder:1.5
Exponent:91.125


In [ ]:
num = [12,15,18,10,20]
total=0
for x in num:
  total += x
  print(f'Sum up till now is : {total}')
avg=total/len(num)
print(f'Total : {total}')
print(f'Average : {avg}')

Sum up till now is : 12
Sum up till now is : 27
Sum up till now is : 45
Sum up till now is : 55
Sum up till now is : 75
Total : 75
Average : 15.0


In [ ]:
import numpy as np

In [ ]:
marks= np.array([72.1,65.3,81.5,54.4,90.9])

In [ ]:
print(type(marks))

<class 'numpy.ndarray'>


In [ ]:
a = np.array(42)

In [ ]:
print(f'Array:\n{a}')
print(f'dtype:\n{a.dtype}')
print(f'Dimension:\n{a.ndim}')
print(f'shape:\n{a.shape}')
print(f'size:\n{a.size}')

Array:
42
dtype:
int64
Dimension:
0
shape:
()
size:
1


In [ ]:
b= np.array([42,12,15,70])
print(f'Array:\n{b}')
print(f'dtype:\n{b.dtype}')
print(f'Dimension:\n{b.ndim}')
print(f'shape:\n{b.shape}')
print(f'size:\n{b.size}')

Array:
[42 12 15 70]
dtype:
int64
Dimension:
1
shape:
(4,)
size:
4


In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[6,75,8]])
print(f'Array:\n{arr2d}')
print(f'dtype:\n{arr2d.dtype}')
print(f'Dimension:\n{arr2d.ndim}')
print(f'shape:\n{arr2d.shape}')
print(f'size:\n{arr2d.size}')

Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 6 75  8]]
dtype:
int64
Dimension:
2
shape:
(3, 3)
size:
9


In [ ]:
arr3d=np.array([[[1,2,3],[10,20,30],[13,14,15]],[[4,5,6],[5,7,8],[10,11,12]]])
print(f'Array:\n{arr3d}')
print(f'dtype:\n{arr3d.dtype}')
print(f'Dimension:\n{arr3d.ndim}')
print(f'shape:\n{arr3d.shape}')
print(f'size:\n{arr3d.size}')

Array:
[[[ 1  2  3]
  [10 20 30]
  [13 14 15]]

 [[ 4  5  6]
  [ 5  7  8]
  [10 11 12]]]
dtype:
int64
Dimension:
3
shape:
(2, 3, 3)
size:
18


In [ ]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(f'Array:\n{arr2d}')
print(f'dtype:\n{arr2d.dtype}')
print(f'Dimension:\n{arr2d.ndim}')
print(f'shape:\n{arr2d.shape}')
print(f'size:\n{arr2d.size}')

Array:
[[1 2 3]
 [4 5 6]]
dtype:
int64
Dimension:
2
shape:
(2, 3)
size:
6


In [ ]:
print(f'Array:\n{arr2d}')
print(f'Row1,column2:{arr2d[0,1]}')
print(f'Row2,column3:{arr2d[1,2]}')
print(f'Second row: {arr2d[1]}')
print(f'Second column: {arr2d[:,1]}')
print(f'Third column: {arr2d[:,2]}')

Array:
[[1 2 3]
 [4 5 6]]
Row1,column2:2
Row2,column3:6
Second row: [4 5 6]
Second column: [2 5]
Third column: [3 6]


In [ ]:
print(arr3d[1,0,:])

[4 5 6]


In [ ]:
print(arr3d[0,:,2])

[ 3 30 15]


In [ ]:
ar= np.array([45,23,34,56,78,12])
print(f'first four:{ar[:4]}')

first four:[45 23 34 56]


In [ ]:
print(f'middle element:{ar[2:6]}')
print(f'every second value:{ar[::2]}')
print(f'Reverse:{ar[::-1]}')
print(f'Last four:{ar[-4:]}')

middle element:[34 56 78 12]
every second value:[45 34 78]
Reverse:[12 78 56 34 23 45]
Last four:[34 56 78 12]


#create array from scratch

In [ ]:
zeros=np.zeros(5)
print(f'Zeros:{zeros}')
ones=np.ones((2,3))
print(f'Ones:{ones}')
full=np.full((2,3),7)
print(f'full:{full}')

Zeros:[0. 0. 0. 0. 0.]
Ones:[[1. 1. 1.]
 [1. 1. 1.]]
full:[[7 7 7]
 [7 7 7]]


In [ ]:
a=np.arange(0,10,2)
print(f'arange:{a}')

arange:[0 2 4 6 8]


In [ ]:
b=np.linspace(0,10,5)
print(f'linspace:{b}')

linspace:[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#Que. Generate zero to one with 11 points using linspace
c=np.linspace(0,1,11)
print(f'linspace:{c}')

linspace:[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
np.random.seed(5)
rd=np.random.random(5)
print(rd)

[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]


In [ ]:
ri = np.random.randint(1,11,size=5)
print(ri)

[8 1 1 8 2]
